/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class CholeskyNative */

#ifndef _Included_CholeskyNative
#define _Included_CholeskyNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     CholeskyNative
 * Method:    sparseCholesky
 * Signature: ([I[I[F[F[FIIZ)V
 */
JNIEXPORT void JNICALL Java_CholeskyNative_sparseCholesky
  (JNIEnv *, jclass, jintArray, jintArray, jfloatArray, jfloatArray, jfloatArray, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
